import "server-only";

import type { BlogAuthor } from "@/app/data/blogAuthors";
import { pickCategoryForSeoBrief } from "@/lib/cms/blog-author-expertise";
import { pickAuthorForBlogTopic } from "@/lib/cms/authorService";
import type { TopicCategory } from "@/lib/topicCategories";
import {
  pickSeoKeywordBrief,
  type SeoKeywordBrief,
} from "@/lib/seo/keyword-stats";

export type BlogAutomationPlan = {
  seoBrief: SeoKeywordBrief | null;
  category: TopicCategory;
  author: BlogAuthor;
  seoKeyword: string;
};

/**
 * Plan one automation run: keyword → category → best-matching author.
 * (Topic titles and article still generated by Gemini afterward.)
 */
export async function planBlogAutomation(): Promise<BlogAutomationPlan> {
  const seoBrief = await pickSeoKeywordBrief();
  const category = pickCategoryForSeoBrief(seoBrief);
  const seoKeyword = seoBrief?.primary ?? "";
  const author = await pickAuthorForBlogTopic({
    seoKeyword,
    category,
    searchIntent: seoBrief?.searchIntent,
  });

  return { seoBrief, category, author, seoKeyword };
}
